services:
  reverse-proxy:
    build:
      context: ./services/reverse-proxy
      dockerfile: Dockerfile
    env_file:
      - ./services/reverse-proxy/.env
    ports:
      - 8080:80
    depends_on:
      files:
        condition: service_healthy
  files:
    build:
      context: ./services/files
      target: prod
    env_file:
      - ./services/files/.env
    healthcheck:
      test: ['CMD', './healthcheck']
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
